### ISSUE TITLE
Generate PDF scramble sets

### ISSUE THREAD

**Issue by thorsilver** [suphair/speedcubingextraevents.org#1]
I use your site frequently to generate scrambles for kilominx, ivy cube and the curvy copter.  I would really enjoy the ability to generate PDFs like the example scrambles you have available for each event; when practising, it's nice to be able to print out a bunch of scrambles that I can hammer through all in a row without needing to interrupt myself and go back to the computer screen.  I do this with TNoodle for WCA puzzles.

Would it be possible to allow users to generate PDF scramble sets on the site?

**Comment by suphair** [comment]
Yes, it can be done. I'll do it as soon as I can.

**Comment by suphair** [comment]
I did this, please check
